### ISSUE TITLE
Initial Code

### ISSUE THREAD

**Issue by cz2246** [ColumbiaJS/hw2#1]
The main README.md says that the .js files we should edit will contain:

module.exports = function ([param,], param,[..., param]]]) {
  // Your code goes here
};

But they do not. Should we change the files ourselves? If so, gulp gives errors.

**Comment by levbrie** [comment]
@cz2246 Yes, you should now add these.

**Comment by ohEmily** [comment]
Just to be clear, should we replace

```
(function () {
    'use strict';
})();
```

with 

```
module.exports = function ([param,], param,[..., param]]]) {
    // Your code goes here
};
```

Is that right?

**Comment by levbrie** [comment]
@ohEmily 

Close. You want to keep the IIFE and place the `module.exports` inside of it, like this;

``` js
(function () {
  'use strict';
  module.exports = function ([param,], param,[..., param]]]) {
    // Your code goes here
  };
})();
```

Does that make sense?
