### ISSUE TITLE
Spacing Errors in Gulp

### ISSUE THREAD

**Issue by jzf2101** [ColumbiaJS/hw2#5]
I keep encountering spacing issues in my code when I run gulp.  Is there's a straightforward way to resolve whitespace style issues so it conforms with the gulp tests?

**Comment by levbrie** [comment]
@jzf2101 You should set your editor to Indent using spaces with a tab width of 2 for all dotfiles, JavaScript, html, and css files.  In Sublime that setting looks like this:

![screen shot 2015-02-03 at 8 28 22 am](https://cloud.githubusercontent.com/assets/1441307/6020860/c48b3eca-ab7e-11e4-9d03-e14f6a279b68.png)

Let me know if that resolves your issue.
