### ISSUE TITLE
Start of project output after running gulp

### ISSUE THREAD

**Issue by ohEmily** [ColumbiaJS/hw2#6]
(Lev and Morris, sorry I have sort of two issue threads going [one on my personal repo]. I'll try to move the discussion here.)

After commenting out lines 8 and 21 in `gulpfile.js`, running gulp yields the following error. I just wanted to make sure that my environment is now set up properly and that this is the expected output.

![image](https://cloud.githubusercontent.com/assets/4631633/6054572/21875d36-acbd-11e4-8b03-7a950537d3a7.png)

Thanks!
-Emily

**Comment by morrishopkins** [comment]
Hi Emily,

Yes I that looks correct.

-Morris

**Comment by levbrie** [comment]
Yup!
